version: '2'

services:
  redis:
    command: redis-server --appendonly yes
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
    driver: local
