require 'rubygems'
require 'webmock/rspec'
require 'faker'

RSpec.configure do |config|
  config.color = true
  config.formatter = :documentation

  config.mock_with :rspec
  config.expect_with :rspec
  config.raise_errors_for_deprecations!
end

MEMBERS_JSON = '[
    {
        "login": "electrical",
        "id": 271677,
        "avatar_url": "https://avatars.githubusercontent.com/u/271677?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/electrical",
        "html_url": "https://github.com/electrical",
        "followers_url": "https://api.github.com/users/electrical/followers",
        "following_url": "https://api.github.com/users/electrical/following{/other_user}",
        "gists_url": "https://api.github.com/users/electrical/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/electrical/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/electrical/subscriptions",
        "organizations_url": "https://api.github.com/users/electrical/orgs",
        "repos_url": "https://api.github.com/users/electrical/repos",
        "events_url": "https://api.github.com/users/electrical/events{/privacy}",
        "received_events_url": "https://api.github.com/users/electrical/received_events",
        "type": "User",
        "site_admin": false
    },
    {
        "login": "pyr",
        "id": 110280,
        "avatar_url": "https://avatars.githubusercontent.com/u/110280?v=3",
        "gravatar_id": "",
        "url": "https://api.github.com/users/pyr",
        "html_url": "https://github.com/pyr",
        "followers_url": "https://api.github.com/users/pyr/followers",
        "following_url": "https://api.github.com/users/pyr/following{/other_user}",
        "gists_url": "https://api.github.com/users/pyr/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/pyr/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/pyr/subscriptions",
        "organizations_url": "https://api.github.com/users/pyr/orgs",
        "repos_url": "https://api.github.com/users/pyr/repos",
        "events_url": "https://api.github.com/users/pyr/events{/privacy}",
        "received_events_url": "https://api.github.com/users/pyr/received_events",
        "type": "User",
        "site_admin": false
    }
]'

ELECTRICAL_REPOS = '[
    {
        "id": 50601531,
        "name": "ansible-elasticsearch",
        "full_name": "electrical/ansible-elasticsearch",
        "owner": {
            "login": "electrical",
            "id": 271677,
            "avatar_url": "https://avatars.githubusercontent.com/u/271677?v=3",
            "gravatar_id": "",
            "url": "https://api.github.com/users/electrical",
            "html_url": "https://github.com/electrical",
            "followers_url": "https://api.github.com/users/electrical/followers",
            "following_url": "https://api.github.com/users/electrical/following{/other_user}",
            "gists_url": "https://api.github.com/users/electrical/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/electrical/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/electrical/subscriptions",
            "organizations_url": "https://api.github.com/users/electrical/orgs",
            "repos_url": "https://api.github.com/users/electrical/repos",
            "events_url": "https://api.github.com/users/electrical/events{/privacy}",
            "received_events_url": "https://api.github.com/users/electrical/received_events",
            "type": "User",
            "site_admin": false
        },
        "private": false,
        "html_url": "https://github.com/electrical/ansible-elasticsearch",
        "description": "Ansible playbook for Elasticsearch",
        "fork": true,
        "url": "https://api.github.com/repos/electrical/ansible-elasticsearch",
        "forks_url": "https://api.github.com/repos/electrical/ansible-elasticsearch/forks",
        "keys_url": "https://api.github.com/repos/electrical/ansible-elasticsearch/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/electrical/ansible-elasticsearch/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/electrical/ansible-elasticsearch/teams",
        "hooks_url": "https://api.github.com/repos/electrical/ansible-elasticsearch/hooks",
        "issue_events_url": "https://api.github.com/repos/electrical/ansible-elasticsearch/issues/events{/number}",
        "events_url": "https://api.github.com/repos/electrical/ansible-elasticsearch/events",
        "assignees_url": "https://api.github.com/repos/electrical/ansible-elasticsearch/assignees{/user}",
        "branches_url": "https://api.github.com/repos/electrical/ansible-elasticsearch/branches{/branch}",
        "tags_url": "https://api.github.com/repos/electrical/ansible-elasticsearch/tags",
        "blobs_url": "https://api.github.com/repos/electrical/ansible-elasticsearch/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/electrical/ansible-elasticsearch/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/electrical/ansible-elasticsearch/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/electrical/ansible-elasticsearch/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/electrical/ansible-elasticsearch/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/electrical/ansible-elasticsearch/languages",
        "stargazers_url": "https://api.github.com/repos/electrical/ansible-elasticsearch/stargazers",
        "contributors_url": "https://api.github.com/repos/electrical/ansible-elasticsearch/contributors",
        "subscribers_url": "https://api.github.com/repos/electrical/ansible-elasticsearch/subscribers",
        "subscription_url": "https://api.github.com/repos/electrical/ansible-elasticsearch/subscription",
        "commits_url": "https://api.github.com/repos/electrical/ansible-elasticsearch/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/electrical/ansible-elasticsearch/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/electrical/ansible-elasticsearch/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/electrical/ansible-elasticsearch/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/electrical/ansible-elasticsearch/contents/{+path}",
        "compare_url": "https://api.github.com/repos/electrical/ansible-elasticsearch/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/electrical/ansible-elasticsearch/merges",
        "archive_url": "https://api.github.com/repos/electrical/ansible-elasticsearch/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/electrical/ansible-elasticsearch/downloads",
        "issues_url": "https://api.github.com/repos/electrical/ansible-elasticsearch/issues{/number}",
        "pulls_url": "https://api.github.com/repos/electrical/ansible-elasticsearch/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/electrical/ansible-elasticsearch/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/electrical/ansible-elasticsearch/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/electrical/ansible-elasticsearch/labels{/name}",
        "releases_url": "https://api.github.com/repos/electrical/ansible-elasticsearch/releases{/id}",
        "deployments_url": "https://api.github.com/repos/electrical/ansible-elasticsearch/deployments",
        "created_at": "2016-01-28T17:49:38Z",
        "updated_at": "2016-01-28T17:49:38Z",
        "pushed_at": "2016-01-28T17:49:45Z",
        "git_url": "git://github.com/electrical/ansible-elasticsearch.git",
        "ssh_url": "git@github.com:electrical/ansible-elasticsearch.git",
        "clone_url": "https://github.com/electrical/ansible-elasticsearch.git",
        "svn_url": "https://github.com/electrical/ansible-elasticsearch",
        "homepage": null,
        "size": 118,
        "stargazers_count": 0,
        "watchers_count": 0,
        "language": "Ruby",
        "has_issues": false,
        "has_downloads": true,
        "has_wiki": true,
        "has_pages": false,
        "forks_count": 0,
        "mirror_url": null,
        "open_issues_count": 0,
        "forks": 0,
        "open_issues": 0,
        "watchers": 0,
        "default_branch": "master"
    }
]'

PYR_REPOS = '[
  {
    "id": 51502454,
    "name": "alia",
    "full_name": "pyr/alia",
    "owner": {
      "login": "pyr",
      "id": 110280,
      "avatar_url": "https://avatars.githubusercontent.com/u/110280?v=3",
      "gravatar_id": "",
      "url": "https://api.github.com/users/pyr",
      "html_url": "https://github.com/pyr",
      "followers_url": "https://api.github.com/users/pyr/followers",
      "following_url": "https://api.github.com/users/pyr/following{/other_user}",
      "gists_url": "https://api.github.com/users/pyr/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/pyr/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/pyr/subscriptions",
      "organizations_url": "https://api.github.com/users/pyr/orgs",
      "repos_url": "https://api.github.com/users/pyr/repos",
      "events_url": "https://api.github.com/users/pyr/events{/privacy}",
      "received_events_url": "https://api.github.com/users/pyr/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/pyr/alia",
    "description": "High performance Cassandra client for clojure",
    "fork": true,
    "url": "https://api.github.com/repos/pyr/alia",
    "forks_url": "https://api.github.com/repos/pyr/alia/forks",
    "keys_url": "https://api.github.com/repos/pyr/alia/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/pyr/alia/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/pyr/alia/teams",
    "hooks_url": "https://api.github.com/repos/pyr/alia/hooks",
    "issue_events_url": "https://api.github.com/repos/pyr/alia/issues/events{/number}",
    "events_url": "https://api.github.com/repos/pyr/alia/events",
    "assignees_url": "https://api.github.com/repos/pyr/alia/assignees{/user}",
    "branches_url": "https://api.github.com/repos/pyr/alia/branches{/branch}",
    "tags_url": "https://api.github.com/repos/pyr/alia/tags",
    "blobs_url": "https://api.github.com/repos/pyr/alia/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/pyr/alia/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/pyr/alia/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/pyr/alia/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/pyr/alia/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/pyr/alia/languages",
    "stargazers_url": "https://api.github.com/repos/pyr/alia/stargazers",
    "contributors_url": "https://api.github.com/repos/pyr/alia/contributors",
    "subscribers_url": "https://api.github.com/repos/pyr/alia/subscribers",
    "subscription_url": "https://api.github.com/repos/pyr/alia/subscription",
    "commits_url": "https://api.github.com/repos/pyr/alia/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/pyr/alia/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/pyr/alia/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/pyr/alia/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/pyr/alia/contents/{+path}",
    "compare_url": "https://api.github.com/repos/pyr/alia/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/pyr/alia/merges",
    "archive_url": "https://api.github.com/repos/pyr/alia/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/pyr/alia/downloads",
    "issues_url": "https://api.github.com/repos/pyr/alia/issues{/number}",
    "pulls_url": "https://api.github.com/repos/pyr/alia/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/pyr/alia/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/pyr/alia/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/pyr/alia/labels{/name}",
    "releases_url": "https://api.github.com/repos/pyr/alia/releases{/id}",
    "deployments_url": "https://api.github.com/repos/pyr/alia/deployments",
    "created_at": "2016-02-11T08:30:50Z",
    "updated_at": "2016-02-11T08:30:51Z",
    "pushed_at": "2016-02-08T15:13:19Z",
    "git_url": "git://github.com/pyr/alia.git",
    "ssh_url": "git@github.com:pyr/alia.git",
    "clone_url": "https://github.com/pyr/alia.git",
    "svn_url": "https://github.com/pyr/alia",
    "homepage": "https://mpenet.github.io/alia/qbits.alia.html#docs",
    "size": 1139,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "Clojure",
    "has_issues": false,
    "has_downloads": true,
    "has_wiki": false,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master"
  }
]'
